# Generated by Django 4.2.8 on 2023-12-09 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_name', models.TextField()),
                ('secondary_name', models.TextField()),
                ('third_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('birthday', models.DateTimeField()),
                ('phone_number', models.CharField(max_length=10)),
                ('date_of_fitting', models.DateTimeField()),
                ('warranty_expiration', models.DateTimeField()),
                ('cost_of_reimbursement', models.IntegerField()),
                ('primary_insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_insurance_patients', to='core.insurance')),
                ('secondary_insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_insurance_patients', to='core.insurance')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
