# Generated by Django 4.2.8 on 2023-12-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_log_user_alter_patient_primary_insurance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
